### ISSUE TITLE
Error in Cell 21

### ISSUE THREAD

**Issue by MartinPeris** [tensorflow/swift-tutorials#9]
Going through https://colab.research.google.com/github/tensorflow/swift-tutorials/blob/master/iris/swift_tensorflow_tutorial.ipynb#scrollTo=wr5A5WvthvZ0 I get the following error.

I notice just a few minutes ago there was a commit mentioning some API changes (https://github.com/tensorflow/swift-tutorials/commit/0ece36b4d7eb11626c8c621897a45b5668cfc69f) maybe something broke?

(I didn't touch anything, I swear  0:-))

```
error: <Cell 21>:18:55: error: use of undeclared type 'Context'
    func applied(to input: Tensor<Float>, in context: Context) -> Tensor<Float> {
                                                      ^~~~~~~

error: <Cell 21>:5:8: error: type 'DenseLayer' does not conform to protocol 'Layer'
struct DenseLayer : Layer {
       ^
```

**Comment by rxwei** [comment]
This is because the default Swift toolchain in Colab updates every 3 days, but you can follow these [instructions](https://github.com/tensorflow/swift/blob/master/Usage.md#getting-newer-swift-builds) to get the nightly build.

**Comment by MartinPeris** [comment]
I see! Thank you :-*
